apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debezium-ui
  name: debezium-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-ui
  template:
    metadata:
      labels:
        app: debezium-ui
    spec:
      containers:
        - name: debezium-ui
          image: image-registry.openshift-image-registry.svc:5000/debezium-ui-demo/debezium-ui
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DEBEZIUM_BASE_URI
              value: https://localhost/api/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: debezium-ui
  name: debezium-ui
spec:
  type: NodePort
  ports:
    - name: debezium-ui-port
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: debezium-ui
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: debezium-ui
  name: debezium-ui
spec:
  port:
    targetPort: debezium-ui-port
  to:
    kind: Service
    name: debezium-ui
    weight: 100
